import Route from '@ember/routing/route';

export default Route.extend({
  model() {
    return [{"artist":"Nolana Codron","album":"nunc","service":"Youtube","title":"lorem id ligula","duration":164},
      {"artist":"Maurine Dimmock","album":"ipsum","service":"Spotify","title":"sapien quis libero nullam","duration":374},
      {"artist":"Kristyn Kennaird","album":"molestie","service":"Spotify","title":"nisi at nibh in","duration":133},
      {"artist":"Anni Sapena","album":"felis fusce","service":"Spotify","title":"amet","duration":424},
      {"artist":"Velma Delbergue","album":"mauris","service":"Youtube","title":"dictumst maecenas ut massa","duration":132},
      {"artist":"Maris Patershall","album":"elit","service":"Youtube","title":"sit","duration":383},
      {"artist":"Felice Stubbings","album":"rhoncus","service":"Youtube","title":"erat volutpat in congue","duration":307},
      {"artist":"Isahella Janaszkiewicz","album":"sapien","service":"Youtube","title":"sit amet justo","duration":491},
      {"artist":"Willy Saunders","album":"sapien in","service":"Youtube","title":"velit","duration":435},
      {"artist":"Markos Arkcoll","album":"porttitor","service":"Youtube","title":"quam pharetra","duration":410},
      {"artist":"Opaline Longcake","album":"quisque","service":"Youtube","title":"sed augue","duration":257},
      {"artist":"Donella McGovern","album":"varius","service":"Spotify","title":"tincidunt ante vel ipsum","duration":216},
      {"artist":"Lorant Peplaw","album":"quam turpis","service":"Spotify","title":"amet erat nulla tempus","duration":404},
      {"artist":"Tabor Lindblad","album":"ut odio","service":"Spotify","title":"ut","duration":322},
      {"artist":"Kevan Catcheside","album":"vivamus","service":"Youtube","title":"ligula nec","duration":476},
      {"artist":"Gris McDarmid","album":"phasellus id","service":"Spotify","title":"ipsum","duration":185},
      {"artist":"Jose Geldart","album":"at","service":"Spotify","title":"potenti","duration":234},
      {"artist":"Jacobo Veregan","album":"quam","service":"Spotify","title":"nullam varius","duration":486},
      {"artist":"Merilyn Alfonsetto","album":"tellus semper","service":"Youtube","title":"lobortis sapien sapien non","duration":331},
      {"artist":"Cherianne Blaszczynski","album":"magna at","service":"Spotify","title":"eu orci","duration":200},
      {"artist":"Marylee Klausen","album":"nibh in","service":"Spotify","title":"convallis nunc proin","duration":439},
      {"artist":"Layne Dupre","album":"ut rhoncus","service":"Spotify","title":"in","duration":363},
      {"artist":"Berne Vidgeon","album":"mattis","service":"Youtube","title":"amet","duration":383},
      {"artist":"Shirl Slee","album":"vel","service":"Youtube","title":"pede","duration":272},
      {"artist":"Talya Ambrogioni","album":"condimentum id","service":"Spotify","title":"in libero ut massa","duration":103},
      {"artist":"Fabiano Cyson","album":"purus","service":"Youtube","title":"at feugiat non pretium","duration":329},
      {"artist":"Harrietta Coltman","album":"convallis eget","service":"Youtube","title":"ornare consequat lectus","duration":374},
      {"artist":"Coraline Bineham","album":"sem","service":"Youtube","title":"neque aenean auctor","duration":204},
      {"artist":"Alfie Casswell","album":"justo","service":"Spotify","title":"sem","duration":367},
      {"artist":"Colver Salerg","album":"curabitur","service":"Spotify","title":"justo lacinia eget tincidunt","duration":411},
      {"artist":"Gates Geffen","album":"ipsum","service":"Youtube","title":"penatibus","duration":420},
      {"artist":"Ker Ingle","album":"ornare","service":"Spotify","title":"lacinia","duration":393},
      {"artist":"Silvester Bonhill","album":"augue","service":"Youtube","title":"ullamcorper purus","duration":168},
      {"artist":"Tybalt Baseley","album":"vestibulum","service":"Spotify","title":"pede morbi porttitor","duration":332},
      {"artist":"Casie Coupman","album":"arcu sed","service":"Youtube","title":"suscipit nulla elit ac","duration":282},
      {"artist":"Paige Le Barre","album":"sit","service":"Youtube","title":"et ultrices posuere cubilia","duration":182},
      {"artist":"Aliza Hagard","album":"a suscipit","service":"Spotify","title":"lectus in","duration":397},
      {"artist":"Cassi Loveridge","album":"nullam","service":"Youtube","title":"lectus pellentesque eget nunc","duration":489},
      {"artist":"Dougy Cribbins","album":"justo","service":"Youtube","title":"eget orci","duration":485},
      {"artist":"Robinette Deason","album":"in","service":"Youtube","title":"ipsum dolor sit","duration":407},
      {"artist":"Oberon Van Castele","album":"congue elementum","service":"Spotify","title":"condimentum neque","duration":245},
      {"artist":"Sonnie Willgrass","album":"pharetra magna","service":"Spotify","title":"est quam","duration":338},
      {"artist":"Aurora Birkin","album":"iaculis justo","service":"Youtube","title":"sapien","duration":460},
      {"artist":"Rachael Kilban","album":"quisque","service":"Youtube","title":"blandit mi in","duration":159},
      {"artist":"Kristal Dalla","album":"phasellus id","service":"Youtube","title":"diam vitae quam suspendisse","duration":492},
      {"artist":"Mercedes Exon","album":"pretium iaculis","service":"Youtube","title":"feugiat et","duration":213},
      {"artist":"Des FitzAlan","album":"magna vulputate","service":"Spotify","title":"pede justo lacinia","duration":221},
      {"artist":"Jennie Maddrell","album":"augue quam","service":"Youtube","title":"mi nulla ac enim","duration":353},
      {"artist":"Letta Perrins","album":"nulla tellus","service":"Youtube","title":"dictumst morbi vestibulum velit","duration":247},
      {"artist":"Samson McNeilly","album":"tellus","service":"Spotify","title":"cras","duration":164},
      {"artist":"Kennett Battrum","album":"et tempus","service":"Spotify","title":"habitasse platea dictumst","duration":105},
      {"artist":"Bil Hyde-Chambers","album":"proin","service":"Youtube","title":"arcu libero rutrum","duration":352},
      {"artist":"Fancie Fitkin","album":"eget elit","service":"Youtube","title":"habitasse","duration":148},
      {"artist":"Ediva Wipper","album":"nec euismod","service":"Youtube","title":"amet turpis elementum ligula","duration":198},
      {"artist":"Duky Sabathe","album":"consequat metus","service":"Spotify","title":"fusce congue","duration":323},
      {"artist":"Em Gulliman","album":"elit ac","service":"Youtube","title":"nulla facilisi cras non","duration":266},
      {"artist":"Solomon Patridge","album":"nulla","service":"Spotify","title":"in lacus curabitur","duration":326},
      {"artist":"Rayshell Banishevitz","album":"urna","service":"Spotify","title":"gravida nisi at nibh","duration":107},
      {"artist":"Malachi Udie","album":"nunc","service":"Spotify","title":"ipsum integer a nibh","duration":271},
      {"artist":"Salvador Oaks","album":"in felis","service":"Spotify","title":"odio","duration":496},
      {"artist":"Rheba Fer","album":"id","service":"Youtube","title":"magna vulputate","duration":439},
      {"artist":"Gerda Gyorffy","album":"dapibus augue","service":"Youtube","title":"semper rutrum nulla nunc","duration":310},
      {"artist":"Llywellyn Karpychev","album":"pulvinar lobortis","service":"Youtube","title":"sed","duration":409},
      {"artist":"Carny Ecles","album":"ac","service":"Spotify","title":"posuere","duration":348},
      {"artist":"Edan Bartens","album":"at ipsum","service":"Youtube","title":"rutrum rutrum neque aenean","duration":490},
      {"artist":"Worthington Fittall","album":"ultrices","service":"Spotify","title":"curabitur convallis duis","duration":341},
      {"artist":"Fionnula Iddiens","album":"donec","service":"Youtube","title":"et ultrices posuere","duration":250},
      {"artist":"Sophey Dodge","album":"pede","service":"Spotify","title":"pede libero quis orci","duration":457},
      {"artist":"Royce MacFarland","album":"varius","service":"Youtube","title":"ipsum ac tellus","duration":116},
      {"artist":"Gregor Crookshank","album":"libero","service":"Spotify","title":"blandit ultrices enim","duration":158},
      {"artist":"Hall Carthy","album":"ante","service":"Youtube","title":"suscipit nulla","duration":272},
      {"artist":"Elane Iston","album":"auctor sed","service":"Spotify","title":"diam in magna","duration":310},
      {"artist":"Corrine Hotton","album":"id","service":"Spotify","title":"ligula nec sem duis","duration":149},
      {"artist":"Lilith Cartan","album":"vestibulum sagittis","service":"Spotify","title":"eros","duration":148},
      {"artist":"Elfie Kohneke","album":"molestie","service":"Youtube","title":"posuere","duration":330},
      {"artist":"Scarlett Flear","album":"neque","service":"Youtube","title":"nec","duration":426},
      {"artist":"Marielle Over","album":"nulla dapibus","service":"Youtube","title":"convallis duis","duration":473},
      {"artist":"Velma Duddle","album":"diam","service":"Spotify","title":"blandit lacinia erat","duration":254},
      {"artist":"Cosme Lund","album":"justo","service":"Youtube","title":"et magnis","duration":364},
      {"artist":"Cynde Willson","album":"nascetur ridiculus","service":"Youtube","title":"ipsum primis in faucibus","duration":222},
      {"artist":"Otho Gadesby","album":"convallis","service":"Spotify","title":"nec sem duis","duration":471},
      {"artist":"Orbadiah MacEntee","album":"mattis","service":"Youtube","title":"dolor vel est donec","duration":367},
      {"artist":"Padriac Lukash","album":"nulla","service":"Youtube","title":"pharetra","duration":421},
      {"artist":"Franklyn Bourdas","album":"porttitor","service":"Youtube","title":"mauris","duration":259},
      {"artist":"Ingrim Madgett","album":"massa donec","service":"Youtube","title":"morbi odio odio","duration":352},
      {"artist":"Gibby Vautre","album":"lorem","service":"Spotify","title":"eu","duration":376},
      {"artist":"Simone Duplan","album":"ridiculus mus","service":"Youtube","title":"in leo","duration":416},
      {"artist":"Kristel Popescu","album":"tellus semper","service":"Spotify","title":"duis faucibus accumsan","duration":448},
      {"artist":"Matteo Ingerson","album":"sed lacus","service":"Spotify","title":"cras mi pede","duration":392},
      {"artist":"Merridie Sarsfield","album":"ac nulla","service":"Spotify","title":"ac nulla sed vel","duration":236},
      {"artist":"Gannie Sherington","album":"posuere","service":"Spotify","title":"sit amet eros","duration":168},
      {"artist":"Sean Nordass","album":"augue vestibulum","service":"Youtube","title":"lectus suspendisse","duration":461},
      {"artist":"Jules Linsey","album":"felis donec","service":"Youtube","title":"aliquet at feugiat non","duration":365},
      {"artist":"Mireille Zimmermanns","album":"volutpat sapien","service":"Spotify","title":"nisi venenatis tristique fusce","duration":136},
      {"artist":"Toiboid Dutteridge","album":"sed ante","service":"Spotify","title":"sapien varius ut","duration":324},
      {"artist":"Clotilda Loveitt","album":"nunc","service":"Youtube","title":"erat tortor sollicitudin mi","duration":203},
      {"artist":"Dur Dudney","album":"eu est","service":"Youtube","title":"magna","duration":278},
      {"artist":"Elsi Mc Cahey","album":"lacus","service":"Youtube","title":"ut rhoncus aliquet pulvinar","duration":264},
      {"artist":"My McTerrelly","album":"nisl","service":"Youtube","title":"ut massa","duration":152},
      {"artist":"Paolina Ebsworth","album":"cras","service":"Spotify","title":"tincidunt nulla mollis molestie","duration":349},
      {"artist":"Neda Tesyro","album":"risus semper","service":"Youtube","title":"rutrum ac","duration":423},
      {"artist":"Morlee Extence","album":"dictumst","service":"Spotify","title":"ornare consequat lectus","duration":232},
      {"artist":"Ora Pietasch","album":"nulla justo","service":"Spotify","title":"amet eros suspendisse accumsan","duration":342},
      {"artist":"Jonis Sighard","album":"dignissim vestibulum","service":"Youtube","title":"velit id pretium iaculis","duration":482},
      {"artist":"Pepita Cristea","album":"metus sapien","service":"Youtube","title":"id ligula suspendisse ornare","duration":489},
      {"artist":"Jerrilee Fiddiman","album":"amet consectetuer","service":"Spotify","title":"quisque erat","duration":311},
      {"artist":"Giulio Connor","album":"arcu","service":"Spotify","title":"ac nulla sed","duration":368},
      {"artist":"Henderson Terry","album":"eros elementum","service":"Spotify","title":"odio curabitur convallis","duration":355},
      {"artist":"Pearle Sollett","album":"sapien cursus","service":"Spotify","title":"natoque penatibus et magnis","duration":369},
      {"artist":"Noak Bough","album":"ut massa","service":"Spotify","title":"nec sem duis aliquam","duration":112},
      {"artist":"Opal Marczyk","album":"ipsum","service":"Spotify","title":"in quam","duration":267},
      {"artist":"Wendell Brogan","album":"pellentesque","service":"Youtube","title":"quisque","duration":169},
      {"artist":"Piper Schimpke","album":"non","service":"Spotify","title":"suspendisse accumsan tortor","duration":365},
      {"artist":"Noby Haglinton","album":"quis","service":"Spotify","title":"lectus","duration":323},
      {"artist":"Sephira Monday","album":"id turpis","service":"Youtube","title":"quis turpis","duration":236},
      {"artist":"Gretchen Eve","album":"ac","service":"Youtube","title":"penatibus et magnis dis","duration":326},
      {"artist":"Lin Brelsford","album":"a odio","service":"Spotify","title":"vivamus metus arcu","duration":207},
      {"artist":"Carline Conklin","album":"curabitur","service":"Youtube","title":"praesent","duration":161},
      {"artist":"Hestia Emanuel","album":"leo odio","service":"Spotify","title":"vitae nisl aenean lectus","duration":392},
      {"artist":"Lewiss Zanelli","album":"tortor","service":"Youtube","title":"in faucibus","duration":340},
      {"artist":"Keefer Elstob","album":"purus aliquet","service":"Spotify","title":"praesent lectus","duration":416},
      {"artist":"Uri Hiorn","album":"sed accumsan","service":"Youtube","title":"velit eu est","duration":149},
      {"artist":"Glynda Von Helmholtz","album":"integer","service":"Spotify","title":"hac habitasse platea dictumst","duration":500},
      {"artist":"Ardyth Muttitt","album":"etiam","service":"Spotify","title":"nulla","duration":151},
      {"artist":"Colin Goodacre","album":"ut","service":"Spotify","title":"at diam","duration":319},
      {"artist":"Veronica Buggs","album":"in eleifend","service":"Youtube","title":"vel pede morbi","duration":466},
      {"artist":"Grady Jedrzej","album":"tincidunt eget","service":"Spotify","title":"ut blandit","duration":123},
      {"artist":"Lamond Romero","album":"mauris enim","service":"Youtube","title":"duis","duration":259},
      {"artist":"Gordon McTear","album":"ornare imperdiet","service":"Spotify","title":"semper interdum mauris ullamcorper","duration":450},
      {"artist":"Wilhelmine Brougham","album":"rutrum","service":"Youtube","title":"donec","duration":496},
      {"artist":"Melody Treagust","album":"in tempor","service":"Youtube","title":"convallis nunc","duration":290},
      {"artist":"James Delahunty","album":"sem mauris","service":"Youtube","title":"blandit nam nulla","duration":136},
      {"artist":"Lonna Whife","album":"a","service":"Spotify","title":"in tempus","duration":113},
      {"artist":"Erick Eakly","album":"eu","service":"Youtube","title":"lacinia sapien quis libero","duration":376},
      {"artist":"Korey Swain","album":"donec pharetra","service":"Youtube","title":"semper","duration":307},
      {"artist":"Fidelity Penton","album":"cubilia","service":"Youtube","title":"vestibulum","duration":324},
      {"artist":"Drucie Bretherick","album":"amet","service":"Spotify","title":"sem duis aliquam convallis","duration":442},
      {"artist":"Maximilien Navein","album":"amet sapien","service":"Youtube","title":"cubilia curae nulla dapibus","duration":279},
      {"artist":"Marji Ledgley","album":"sed","service":"Spotify","title":"nonummy maecenas","duration":209},
      {"artist":"Lianne McGibbon","album":"luctus tincidunt","service":"Youtube","title":"commodo placerat praesent blandit","duration":105},
      {"artist":"Elle Wilstead","album":"curabitur gravida","service":"Spotify","title":"augue","duration":328},
      {"artist":"Lindsey Keeri","album":"in quis","service":"Youtube","title":"in hac habitasse","duration":348},
      {"artist":"Josiah Jinks","album":"suspendisse potenti","service":"Spotify","title":"habitasse platea dictumst","duration":342},
      {"artist":"Maribel Vedenyapin","album":"faucibus orci","service":"Youtube","title":"sit amet eros","duration":318},
      {"artist":"Purcell Dwine","album":"posuere cubilia","service":"Youtube","title":"mattis pulvinar","duration":304},
      {"artist":"Justinian Dooney","album":"nulla","service":"Youtube","title":"a ipsum","duration":378},
      {"artist":"Edithe Lemonby","album":"dapibus nulla","service":"Spotify","title":"molestie","duration":362},
      {"artist":"Martin Moncaster","album":"accumsan tellus","service":"Spotify","title":"ullamcorper purus sit","duration":465},
      {"artist":"Earl Shovlin","album":"donec","service":"Youtube","title":"praesent blandit lacinia erat","duration":405},
      {"artist":"Silas Mathivet","album":"dictumst maecenas","service":"Spotify","title":"risus semper","duration":490},
      {"artist":"Abbe Jee","album":"dapibus","service":"Spotify","title":"vel augue vestibulum ante","duration":278},
      {"artist":"Orelee Esler","album":"a odio","service":"Spotify","title":"morbi non","duration":203},
      {"artist":"Stace Garrique","album":"pede posuere","service":"Spotify","title":"sed vel enim sit","duration":212},
      {"artist":"Konstantine Utteridge","album":"potenti nullam","service":"Spotify","title":"vel ipsum praesent blandit","duration":396},
      {"artist":"Ardelle Luca","album":"sagittis dui","service":"Spotify","title":"amet turpis elementum ligula","duration":180},
      {"artist":"Mata Dredge","album":"varius nulla","service":"Youtube","title":"massa volutpat convallis","duration":335},
      {"artist":"Ainslie Inge","album":"scelerisque","service":"Spotify","title":"ligula","duration":211},
      {"artist":"Reyna Marxsen","album":"nulla","service":"Youtube","title":"ut mauris","duration":311},
      {"artist":"Martino Hutcheson","album":"nulla tellus","service":"Spotify","title":"integer tincidunt ante","duration":288},
      {"artist":"Enrichetta Retallack","album":"dictumst","service":"Spotify","title":"posuere cubilia curae duis","duration":469},
      {"artist":"Mechelle Grayston","album":"libero non","service":"Youtube","title":"odio consequat","duration":455},
      {"artist":"Lacee Stritton","album":"nec","service":"Youtube","title":"leo rhoncus sed","duration":375},
      {"artist":"Myrtice Woodhams","album":"justo","service":"Spotify","title":"leo","duration":260},
      {"artist":"Scotti Biggans","album":"curabitur","service":"Spotify","title":"a","duration":108},
      {"artist":"Lorrayne Johanchon","album":"dolor","service":"Spotify","title":"dui proin leo odio","duration":440},
      {"artist":"Griselda Grouse","album":"orci nullam","service":"Spotify","title":"semper interdum","duration":254},
      {"artist":"Bartel Bartel","album":"consectetuer","service":"Spotify","title":"eu","duration":173},
      {"artist":"Sheffield Flement","album":"at vulputate","service":"Spotify","title":"dolor sit amet consectetuer","duration":422},
      {"artist":"Nadean McGahy","album":"enim blandit","service":"Youtube","title":"urna","duration":131},
      {"artist":"Dodi Nutbeam","album":"donec","service":"Spotify","title":"orci nullam","duration":198},
      {"artist":"Rowland Bowkett","album":"penatibus et","service":"Spotify","title":"sodales scelerisque mauris sit","duration":424},
      {"artist":"Dov Morrish","album":"cursus","service":"Spotify","title":"mauris ullamcorper purus","duration":112},
      {"artist":"Huey Leask","album":"et ultrices","service":"Spotify","title":"magna bibendum imperdiet","duration":460},
      {"artist":"Justine Pim","album":"sed","service":"Spotify","title":"erat id mauris vulputate","duration":381},
      {"artist":"Delia Snazle","album":"vitae","service":"Spotify","title":"augue aliquam erat","duration":152},
      {"artist":"Evelyn Kimber","album":"quis","service":"Spotify","title":"varius nulla","duration":372},
      {"artist":"Callean Wrightham","album":"vitae nisl","service":"Spotify","title":"eleifend pede libero","duration":436},
      {"artist":"Angeline Foulser","album":"tempus","service":"Spotify","title":"eget congue eget semper","duration":292},
      {"artist":"Chaddy Manass","album":"lacus curabitur","service":"Youtube","title":"nullam orci pede","duration":241},
      {"artist":"Iggie Lamperd","album":"pharetra magna","service":"Spotify","title":"pulvinar nulla pede","duration":186},
      {"artist":"Ania Lishman","album":"fusce lacus","service":"Youtube","title":"ipsum ac tellus semper","duration":368},
      {"artist":"Jocelyne Canadine","album":"pede","service":"Spotify","title":"vel ipsum praesent","duration":326},
      {"artist":"Bethena Langdon","album":"erat","service":"Youtube","title":"magna bibendum imperdiet","duration":337},
      {"artist":"Anselma Sarl","album":"lacus at","service":"Youtube","title":"quis justo","duration":234},
      {"artist":"Ed Birks","album":"quis","service":"Youtube","title":"habitasse platea","duration":310},
      {"artist":"Kenna Mabb","album":"lectus","service":"Youtube","title":"in","duration":286},
      {"artist":"Gabriel Louisot","album":"in leo","service":"Spotify","title":"nisi at","duration":317},
      {"artist":"Neddy Stockbridge","album":"nulla neque","service":"Youtube","title":"magna vestibulum aliquet ultrices","duration":217},
      {"artist":"Jaime Filchagin","album":"curae donec","service":"Youtube","title":"mus etiam vel","duration":176},
      {"artist":"Tiffanie Dozdill","album":"nisl","service":"Spotify","title":"vitae consectetuer","duration":151},
      {"artist":"Mignon Chesters","album":"vulputate","service":"Youtube","title":"cras","duration":298},
      {"artist":"Nathalie Helsby","album":"rutrum rutrum","service":"Youtube","title":"felis sed","duration":311},
      {"artist":"Cynde Shotboulte","album":"et","service":"Spotify","title":"libero nullam sit","duration":431},
      {"artist":"Gabbie Frankton","album":"rutrum nulla","service":"Spotify","title":"posuere nonummy","duration":390},
      {"artist":"Norina Teague","album":"massa quis","service":"Spotify","title":"risus praesent lectus vestibulum","duration":265},
      {"artist":"Moishe Van Arsdale","album":"dolor vel","service":"Youtube","title":"nisl ut volutpat","duration":123},
      {"artist":"Filmer Combes","album":"ac","service":"Spotify","title":"pede venenatis non","duration":474},
      {"artist":"Cooper Greber","album":"suspendisse potenti","service":"Spotify","title":"eu magna","duration":238},
      {"artist":"Joelie Twelftree","album":"tortor","service":"Spotify","title":"integer pede","duration":241}]
  }
});
